# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 14:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('status', models.IntegerField(default=0, verbose_name='审核状态')),
                ('reason', models.CharField(max_length=200, verbose_name='未通过原因')),
                ('timestamp', models.DateTimeField(default='', verbose_name='发布日期')),
                ('tag', models.CharField(default='', max_length=200, verbose_name='标签')),
                ('publisher', models.CharField(default='', max_length=200, verbose_name='发布人')),
                ('is_enable', models.BooleanField(default=True, verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.NewsCategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
