# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
