# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '文章类别',
                'db_table': 'tb_news_category',
                'verbose_name': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='组号')),
                ('url', models.CharField(max_length=50, verbose_name='频道页面链接')),
                ('sequence', models.IntegerField(verbose_name='组内顺序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.NewsCategory', verbose_name='顶级文章类别')),
            ],
            options={
                'verbose_name_plural': '文章频道',
                'db_table': 'tb_goods_channel',
                'verbose_name': '文章频道',
            },
        ),
    ]
