# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 14:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='广告编号')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='广告内容')),
                ('start_time', models.DateTimeField(default='', verbose_name='开始日期')),
                ('end_time', models.DateTimeField(default='', verbose_name='结束日期')),
                ('hyperlinks', models.CharField(default='', max_length=200, verbose_name='跳转页面url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.NewsCategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
    ]
