# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 15:06
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='广告编号')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='广告内容')),
                ('hyperlinks', models.CharField(default='', max_length=200, verbose_name='跳转页面url')),
            ],
            options={
                'verbose_name': '广告',
                'db_table': 't_ads',
                'verbose_name_plural': '广告',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('status', models.IntegerField(default=0, verbose_name='审核状态')),
                ('reason', models.CharField(max_length=200, verbose_name='未通过原因')),
                ('tag', models.CharField(default='', max_length=200, verbose_name='标签')),
                ('publisher', models.CharField(default='', max_length=200, verbose_name='发布人')),
                ('is_enable', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 't_articles',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
            ],
            options={
                'verbose_name': '类别',
                'db_table': 't_articles_category',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='ArticlesChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('group_id', models.IntegerField(verbose_name='组号')),
                ('url', models.CharField(max_length=50, verbose_name='频道页面链接')),
                ('sequence', models.IntegerField(verbose_name='组内顺序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ArticlesCategory', verbose_name='顶级文章类别')),
            ],
            options={
                'verbose_name': '文章频道',
                'db_table': 'tb_articles_channel',
                'verbose_name_plural': '文章频道',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ArticlesCategory', verbose_name='所属类别'),
        ),
    ]
