# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescategory',
            options={'verbose_name': '文章类别', 'verbose_name_plural': '文章类别'},
        ),
    ]
